version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: soup_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1006
      POSTGRES_DB: soup
    ports:
      - "5433:5432" # local db 생성시 5432 포트 사용 중이면 5433 등으로 변경
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
